version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
